import type { Product, QuickButton } from '../types';

/**
 * Prodotti mock specifici per bar/caffetteria
 */
export const barProducts: Product[] = [
  {
    id: 'bar-1',
    name: 'Caffè Espresso',
    description: 'Caffè espresso classico',
    price: 1.0,
    category: 'Caffetteria',
    stock: 0,
    barcode: '8001234567001',
    image: '',
  },
  {
    id: 'bar-2',
    name: 'Cappuccino',
    description: 'Cappuccino cremoso',
    price: 1.5,
    category: 'Caffetteria',
    stock: 0,
    barcode: '8001234567002',
    image: '',
  },
  {
    id: 'bar-3',
    name: 'Caffè Macchiato',
    description: 'Espresso macchiato',
    price: 1.1,
    category: 'Caffetteria',
    stock: 0,
    barcode: '8001234567003',
    image: '',
  },
  {
    id: 'bar-4',
    name: 'Latte Macchiato',
    description: 'Latte macchiato con caffè',
    price: 1.8,
    category: 'Caffetteria',
    stock: 0,
    barcode: '8001234567004',
    image: '>[',
  },
  {
    id: 'bar-5',
    name: 'Caffè Americano',
    description: 'Caffè lungo americano',
    price: 1.5,
    category: 'Caffetteria',
    stock: 0,
    barcode: '8001234567005',
    image: '',
  },
  {
    id: 'bar-6',
    name: 'Brioche Vuota',
    description: 'Brioche classica vuota',
    price: 1.2,
    category: 'Pasticceria',
    stock: 50,
    barcode: '8001234567006',
    image: '>P',
  },
  {
    id: 'bar-7',
    name: 'Brioche Marmellata',
    description: 'Brioche con marmellata',
    price: 1.5,
    category: 'Pasticceria',
    stock: 40,
    barcode: '8001234567007',
    image: '>P',
  },
  {
    id: 'bar-8',
    name: 'Brioche Crema',
    description: 'Brioche con crema pasticcera',
    price: 1.5,
    category: 'Pasticceria',
    stock: 40,
    barcode: '8001234567008',
    image: '>P',
  },
  {
    id: 'bar-9',
    name: 'Cornetto Cioccolato',
    description: 'Cornetto con cioccolato',
    price: 1.6,
    category: 'Pasticceria',
    stock: 35,
    barcode: '8001234567009',
    image: '>P',
  },
  {
    id: 'bar-10',
    name: 'Acqua Naturale 50cl',
    description: 'Acqua minerale naturale',
    price: 1.0,
    category: 'Bevande',
    stock: 100,
    barcode: '8001234567010',
    image: '=§',
  },
  {
    id: 'bar-11',
    name: 'Acqua Frizzante 50cl',
    description: 'Acqua minerale frizzante',
    price: 1.0,
    category: 'Bevande',
    stock: 100,
    barcode: '8001234567011',
    image: '=§',
  },
  {
    id: 'bar-12',
    name: 'Coca Cola 33cl',
    description: 'Coca Cola lattina',
    price: 2.5,
    category: 'Bevande',
    stock: 80,
    barcode: '8001234567012',
    image: '>d',
  },
  {
    id: 'bar-13',
    name: 'Tè Freddo Limone',
    description: 'Tè freddo al limone',
    price: 2.0,
    category: 'Bevande',
    stock: 60,
    barcode: '8001234567013',
    image: '>Ã',
  },
  {
    id: 'bar-14',
    name: 'Succo Arancia',
    description: 'Succo di arancia 100%',
    price: 2.5,
    category: 'Bevande',
    stock: 50,
    barcode: '8001234567014',
    image: '>Ã',
  },
  {
    id: 'bar-15',
    name: 'Tramezzino Prosciutto',
    description: 'Tramezzino con prosciutto cotto',
    price: 3.0,
    category: 'Snack',
    stock: 30,
    barcode: '8001234567015',
    image: '>j',
  },
  {
    id: 'bar-16',
    name: 'Tramezzino Tonno',
    description: 'Tramezzino con tonno e maionese',
    price: 3.0,
    category: 'Snack',
    stock: 30,
    barcode: '8001234567016',
    image: '>j',
  },
  {
    id: 'bar-17',
    name: 'Toast Prosciutto',
    description: 'Toast con prosciutto e formaggio',
    price: 3.5,
    category: 'Snack',
    stock: 25,
    barcode: '8001234567017',
    image: '>j',
  },
  {
    id: 'bar-18',
    name: 'Piadina',
    description: 'Piadina farcita',
    price: 4.5,
    category: 'Snack',
    stock: 20,
    barcode: '8001234567018',
    image: '</',
  },
];

/**
 * Pulsanti rapidi per vendita veloce
 */
export const quickButtons: QuickButton[] = [
  {
    id: 'qb-1',
    productId: 'bar-1',
    label: 'Caffè',
    color: '#8B4513',
    position: 1,
    category: 'Caffetteria',
  },
  {
    id: 'qb-2',
    productId: 'bar-2',
    label: 'Cappuccino',
    color: '#D2691E',
    position: 2,
    category: 'Caffetteria',
  },
  {
    id: 'qb-3',
    productId: 'bar-3',
    label: 'Macchiato',
    color: '#A0522D',
    position: 3,
    category: 'Caffetteria',
  },
  {
    id: 'qb-4',
    productId: 'bar-4',
    label: 'Latte',
    color: '#DEB887',
    position: 4,
    category: 'Caffetteria',
  },
  {
    id: 'qb-5',
    productId: 'bar-5',
    label: 'Americano',
    color: '#8B4513',
    position: 5,
    category: 'Caffetteria',
  },
  {
    id: 'qb-6',
    productId: 'bar-6',
    label: 'Brioche',
    color: '#F4A460',
    position: 6,
    category: 'Pasticceria',
  },
  {
    id: 'qb-7',
    productId: 'bar-7',
    label: 'B. Marm.',
    color: '#FF6347',
    position: 7,
    category: 'Pasticceria',
  },
  {
    id: 'qb-8',
    productId: 'bar-8',
    label: 'B. Crema',
    color: '#FFD700',
    position: 8,
    category: 'Pasticceria',
  },
  {
    id: 'qb-9',
    productId: 'bar-10',
    label: 'Acqua Nat.',
    color: '#4682B4',
    position: 9,
    category: 'Bevande',
  },
  {
    id: 'qb-10',
    productId: 'bar-11',
    label: 'Acqua Friz.',
    color: '#87CEEB',
    position: 10,
    category: 'Bevande',
  },
  {
    id: 'qb-11',
    productId: 'bar-12',
    label: 'Coca Cola',
    color: '#DC143C',
    position: 11,
    category: 'Bevande',
  },
  {
    id: 'qb-12',
    productId: 'bar-15',
    label: 'Tramezzino',
    color: '#228B22',
    position: 12,
    category: 'Snack',
  },
];
