import type { Product, QuickButton } from '../types';

// Prodotti tipici da BAR
export const barProducts: Product[] = [
  // Caffetteria
  {
    id: 'bar-1',
    name: 'Caffè Espresso',
    description: 'Caffè espresso classico',
    price: 1.20,
    category: 'cat-caffe',
    stock: 999,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-2',
    name: 'Cappuccino',
    description: 'Cappuccino con latte montato',
    price: 1.50,
    category: 'cat-caffe',
    stock: 999,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-3',
    name: 'Caffè Macchiato',
    description: 'Caffè con macchia di latte',
    price: 1.30,
    category: 'cat-caffe',
    stock: 999,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-4',
    name: 'Caffè Americano',
    description: 'Caffè lungo all\'americana',
    price: 1.80,
    category: 'cat-caffe',
    stock: 999,
    taxRate: 10,
    active: true,
  },
  // Bibite
  {
    id: 'bar-5',
    name: 'Coca Cola',
    description: 'Coca Cola lattina 33cl',
    price: 2.50,
    category: 'cat-bibite',
    stock: 150,
    taxRate: 22,
    active: true,
  },
  {
    id: 'bar-6',
    name: 'Acqua Naturale',
    description: 'Acqua naturale 50cl',
    price: 1.00,
    category: 'cat-bibite',
    stock: 200,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-7',
    name: 'Spremuta Arancia',
    description: 'Spremuta fresca d\'arancia',
    price: 3.50,
    category: 'cat-bibite',
    stock: 50,
    taxRate: 10,
    active: true,
  },
  // Cornetteria
  {
    id: 'bar-8',
    name: 'Cornetto Vuoto',
    description: 'Cornetto classico vuoto',
    price: 1.20,
    category: 'cat-cornetti',
    stock: 80,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-9',
    name: 'Cornetto Crema',
    description: 'Cornetto con crema',
    price: 1.50,
    category: 'cat-cornetti',
    stock: 70,
    taxRate: 10,
    active: true,
  },
  {
    id: 'bar-10',
    name: 'Cornetto Nutella',
    description: 'Cornetto ripieno di nutella',
    price: 1.80,
    category: 'cat-cornetti',
    stock: 65,
    taxRate: 10,
    active: true,
  },
  // Tabacchi
  {
    id: 'bar-11',
    name: 'Marlboro Red',
    description: 'Pacchetto Marlboro Red',
    price: 6.00,
    category: 'cat-sigarette',
    barcode: '8000000000001',
    stock: 100,
    taxRate: 22,
    active: true,
  },
  {
    id: 'bar-12',
    name: 'Gratta e Vinci',
    description: 'Gratta e vinci vari',
    price: 5.00,
    category: 'cat-lotterie',
    stock: 200,
    taxRate: 22,
    active: true,
  },
  {
    id: 'bar-13',
    name: 'Ricarica Telefonica',
    description: 'Ricarica telefonica €20',
    price: 20.00,
    category: 'cat-servizi',
    stock: 999,
    taxRate: 22,
    active: true,
  },
];

// Pulsanti rapidi configurabili
export const quickButtons: QuickButton[] = [
  // Riga 1 - Caffè
  {
    id: 'qb-1',
    productId: 'bar-1',
    label: 'CAFFÈ',
    color: 'bg-gradient-to-br from-amber-600 to-amber-800',
    position: 1,
    category: 'caffe',
  },
  {
    id: 'qb-2',
    productId: 'bar-2',
    label: 'CAPPUCCINO',
    color: 'bg-gradient-to-br from-orange-500 to-orange-700',
    position: 2,
    category: 'caffe',
  },
  {
    id: 'qb-3',
    productId: 'bar-3',
    label: 'MACCHIATO',
    color: 'bg-gradient-to-br from-yellow-600 to-amber-700',
    position: 3,
    category: 'caffe',
  },
  {
    id: 'qb-4',
    productId: 'bar-4',
    label: 'AMERICANO',
    color: 'bg-gradient-to-br from-amber-700 to-amber-900',
    position: 4,
    category: 'caffe',
  },
  // Riga 2 - Bibite
  {
    id: 'qb-5',
    productId: 'bar-5',
    label: 'COCA COLA',
    color: 'bg-gradient-to-br from-red-600 to-red-800',
    position: 5,
    category: 'bibite',
  },
  {
    id: 'qb-6',
    productId: 'bar-6',
    label: 'ACQUA',
    color: 'bg-gradient-to-br from-blue-400 to-blue-600',
    position: 6,
    category: 'bibite',
  },
  {
    id: 'qb-7',
    productId: 'bar-7',
    label: 'SPREMUTA',
    color: 'bg-gradient-to-br from-orange-400 to-orange-600',
    position: 7,
    category: 'bibite',
  },
  // Riga 3 - Cornetti
  {
    id: 'qb-8',
    productId: 'bar-8',
    label: 'CORNETTO',
    color: 'bg-gradient-to-br from-yellow-500 to-yellow-700',
    position: 8,
    category: 'cornetti',
  },
  {
    id: 'qb-9',
    productId: 'bar-9',
    label: 'C. CREMA',
    color: 'bg-gradient-to-br from-yellow-400 to-yellow-600',
    position: 9,
    category: 'cornetti',
  },
  {
    id: 'qb-10',
    productId: 'bar-10',
    label: 'C. NUTELLA',
    color: 'bg-gradient-to-br from-amber-700 to-yellow-800',
    position: 10,
    category: 'cornetti',
  },
  // Riga 4 - Altro
  {
    id: 'qb-11',
    productId: 'bar-11',
    label: 'SIGARETTE',
    color: 'bg-gradient-to-br from-gray-600 to-gray-800',
    position: 11,
    category: 'tabacchi',
  },
  {
    id: 'qb-12',
    productId: 'bar-12',
    label: 'GRATTA E VINCI',
    color: 'bg-gradient-to-br from-purple-600 to-purple-800',
    position: 12,
    category: 'lotterie',
  },
];
