import type { Business } from '../types';

// Mock data - in produzione verrebbe da API
export const mockBusinesses: Business[] = [
  // Fashion - Catena boutique alta moda
  {
    id: 'bus-1',
    resellerId: 'res-1',
    companyName: 'Eleganza Fashion Group S.p.A.',
    vatNumber: 'IT02891740967',
    fiscalCode: 'EFG02891740967',
    email: 'info@eleganzafashion.it',
    phone: '+39 02 7601 3456',
    address: 'Via Montenapoleone 8, 20121 Milano',
    website: 'https://www.eleganzafashion.it',
    businessSector: 'fashion',
    active: true,
    createdAt: new Date('2023-06-15'),
    subscriptionPlan: 'professional',
    subscriptionStartDate: new Date('2023-06-15'),
    subscriptionEndDate: new Date('2026-06-15'),
    adminEmail: 'maria.rossi@eleganzafashion.it',
    adminName: 'Maria Rossi',
    adminPassword: 'fashion123',
    maxStores: 5,
    maxOperatorsPerStore: 10,
    billingEmail: 'amministrazione@eleganzafashion.it',
    paymentMethod: 'credit_card',
  },

  // Bar - Catena bar e tabacchi
  {
    id: 'bus-2',
    resellerId: 'res-1',
    companyName: 'Caffè & Tabacchi Da Vinci S.r.l.',
    vatNumber: 'IT03456789012',
    fiscalCode: 'CTD03456789012',
    email: 'gestione@caffedavinci.com',
    phone: '+39 06 6854 2190',
    address: 'Piazza Navona 47, 00186 Roma',
    website: 'https://www.caffedavinci.com',
    businessSector: 'bar',
    active: true,
    createdAt: new Date('2024-01-10'),
    subscriptionPlan: 'basic',
    subscriptionStartDate: new Date('2024-01-10'),
    subscriptionEndDate: new Date('2026-01-10'),
    adminEmail: 'giuseppe.bianchi@caffedavinci.com',
    adminName: 'Giuseppe Bianchi',
    adminPassword: 'caffe123',
    maxStores: 3,
    maxOperatorsPerStore: 5,
    billingEmail: 'contabilita@caffedavinci.com',
    paymentMethod: 'bank_transfer',
  },

  // Restaurant - Ristorante gourmet
  {
    id: 'bus-3',
    resellerId: 'res-1',
    companyName: 'Trattoria Toscana di Verdi & C. S.a.s.',
    vatNumber: 'IT04567890123',
    fiscalCode: 'VRD04567890123',
    email: 'info@trattoriatoscana.it',
    phone: '+39 055 284 735',
    address: 'Via dei Calzaiuoli 32, 50122 Firenze',
    website: 'https://www.trattoriatoscana.it',
    businessSector: 'restaurant',
    active: true,
    createdAt: new Date('2023-03-20'),
    subscriptionPlan: 'professional',
    subscriptionStartDate: new Date('2023-03-20'),
    subscriptionEndDate: new Date('2026-03-20'),
    adminEmail: 'luca.verdi@trattoriatoscana.it',
    adminName: 'Luca Verdi',
    adminPassword: 'toscana123',
    maxStores: 2,
    maxOperatorsPerStore: 15,
    billingEmail: 'amministrazione@trattoriatoscana.it',
    paymentMethod: 'credit_card',
  },

  // Fashion - Negozio abbigliamento sportivo
  {
    id: 'bus-4',
    resellerId: 'res-1',
    companyName: 'SportWear Italia S.r.l.',
    vatNumber: 'IT05678901234',
    email: 'amministrazione@sportwearitalia.it',
    phone: '+39 011 543 8921',
    address: 'Corso Vittorio Emanuele II 76, 10121 Torino',
    website: 'https://www.sportwearitalia.it',
    businessSector: 'fashion',
    active: true,
    createdAt: new Date('2024-02-01'),
    subscriptionPlan: 'basic',
    subscriptionStartDate: new Date('2024-02-01'),
    subscriptionEndDate: new Date('2026-02-01'),
    adminEmail: 'paolo.neri@sportwearitalia.it',
    adminName: 'Paolo Neri',
    adminPassword: 'sport123',
    maxStores: 2,
    maxOperatorsPerStore: 5,
    billingEmail: 'fatture@sportwearitalia.it',
    paymentMethod: 'bank_transfer',
  },

  // Bar - Bar pasticceria
  {
    id: 'bus-5',
    resellerId: 'res-1',
    companyName: 'Dolce Vita Pasticceria S.n.c.',
    vatNumber: 'IT06789012345',
    fiscalCode: 'DVP06789012345',
    email: 'info@dolcevitapasticceria.it',
    phone: '+39 081 764 5321',
    address: 'Via Toledo 156, 80134 Napoli',
    businessSector: 'bar',
    active: true,
    createdAt: new Date('2024-03-15'),
    subscriptionPlan: 'free',
    subscriptionStartDate: new Date('2024-03-15'),
    subscriptionEndDate: new Date('2026-03-15'),
    adminEmail: 'anna.romano@dolcevitapasticceria.it',
    adminName: 'Anna Romano',
    adminPassword: 'dolce123',
    maxStores: 1,
    maxOperatorsPerStore: 3,
    paymentMethod: 'bank_transfer',
  },

  // Restaurant - Pizzeria
  {
    id: 'bus-6',
    resellerId: 'res-1',
    companyName: 'Pizzeria Napoletana Tradizione S.r.l.',
    vatNumber: 'IT07890123456',
    email: 'pizzeria@tradizionenapoli.com',
    phone: '+39 041 528 6743',
    address: 'Campo Santa Maria Formosa 5252, 30122 Venezia',
    website: 'https://www.tradizionenapoli.com',
    businessSector: 'restaurant',
    active: true,
    createdAt: new Date('2023-09-01'),
    subscriptionPlan: 'basic',
    subscriptionStartDate: new Date('2023-09-01'),
    subscriptionEndDate: new Date('2026-09-01'),
    adminEmail: 'marco.esposito@tradizionenapoli.com',
    adminName: 'Marco Esposito',
    adminPassword: 'pizza123',
    maxStores: 2,
    maxOperatorsPerStore: 8,
    billingEmail: 'contabilita@tradizionenapoli.com',
    paymentMethod: 'credit_card',
  },

  // Generic - Cartoleria e giocattoli
  {
    id: 'bus-7',
    resellerId: 'res-1',
    companyName: 'La Matita Magica di Ferretti & Figli',
    vatNumber: 'IT08901234567',
    email: 'info@lamatitamagica.it',
    phone: '+39 051 234 8765',
    address: 'Via Rizzoli 18, 40125 Bologna',
    businessSector: 'generic',
    active: true,
    createdAt: new Date('2024-04-01'),
    subscriptionPlan: 'basic',
    subscriptionStartDate: new Date('2024-04-01'),
    subscriptionEndDate: new Date('2026-04-01'),
    adminEmail: 'carlo.ferretti@lamatitamagica.it',
    adminName: 'Carlo Ferretti',
    adminPassword: 'matita123',
    maxStores: 1,
    maxOperatorsPerStore: 4,
    billingEmail: 'amministrazione@lamatitamagica.it',
    paymentMethod: 'bank_transfer',
  },
];

// Funzione helper per trovare un business per ID
export const getBusinessById = (id: string): Business | undefined => {
  return mockBusinesses.find((b) => b.id === id);
};
