import type { FashionProduct } from '../types';

// Prodotti MODA con varianti taglie/colori
export const fashionProducts: FashionProduct[] = [
  // Maglietta Donna
  {
    id: 'fashion-1',
    name: 'Maglietta Donna Basic',
    description: 'Maglietta in cotone elasticizzato',
    price: 29.90,
    category: 'cat-2',
    barcode: '8020001000001',
    stock: 0, // Stock gestito da varianti
    taxRate: 22,
    active: true,
    brand: 'StyleFit',
    season: 'PE',
    gender: 'donna',
    composition: '95% Cotone, 5% Elastan',
    variants: [
      {
        id: 'var-1-1',
        size: 'XS',
        color: 'Bianco',
        barcode: '8020001000101',
        sku: 'STF-MAG-W-XS',
        stock: 15,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-2',
        size: 'S',
        color: 'Bianco',
        barcode: '8020001000201',
        sku: 'STF-MAG-W-S',
        stock: 20,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-3',
        size: 'M',
        color: 'Bianco',
        barcode: '8020001000301',
        sku: 'STF-MAG-W-M',
        stock: 25,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-4',
        size: 'L',
        color: 'Bianco',
        barcode: '8020001000401',
        sku: 'STF-MAG-W-L',
        stock: 18,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-5',
        size: 'XS',
        color: 'Nero',
        barcode: '8020001000102',
        sku: 'STF-MAG-B-XS',
        stock: 12,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-6',
        size: 'S',
        color: 'Nero',
        barcode: '8020001000202',
        sku: 'STF-MAG-B-S',
        stock: 22,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-7',
        size: 'M',
        color: 'Nero',
        barcode: '8020001000302',
        sku: 'STF-MAG-B-M',
        stock: 30,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-8',
        size: 'L',
        color: 'Nero',
        barcode: '8020001000402',
        sku: 'STF-MAG-B-L',
        stock: 16,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-9',
        size: 'S',
        color: 'Blu Navy',
        barcode: '8020001000203',
        sku: 'STF-MAG-BL-S',
        stock: 10,
        priceAdjustment: 0,
      },
      {
        id: 'var-1-10',
        size: 'M',
        color: 'Blu Navy',
        barcode: '8020001000303',
        sku: 'STF-MAG-BL-M',
        stock: 14,
        priceAdjustment: 0,
      },
    ],
  },

  // Jeans Uomo
  {
    id: 'fashion-2',
    name: 'Jeans Uomo Slim Fit',
    description: 'Jeans elasticizzati slim fit',
    price: 79.90,
    category: 'cat-2',
    barcode: '8020002000001',
    stock: 0,
    taxRate: 22,
    active: true,
    brand: 'DenimPro',
    season: 'AI',
    gender: 'uomo',
    composition: '98% Cotone, 2% Elastan',
    variants: [
      {
        id: 'var-2-1',
        size: '42',
        color: 'Blu Scuro',
        barcode: '8020002000101',
        sku: 'DEN-JEA-BD-42',
        stock: 8,
        priceAdjustment: 0,
      },
      {
        id: 'var-2-2',
        size: '44',
        color: 'Blu Scuro',
        barcode: '8020002000201',
        sku: 'DEN-JEA-BD-44',
        stock: 12,
        priceAdjustment: 0,
      },
      {
        id: 'var-2-3',
        size: '46',
        color: 'Blu Scuro',
        barcode: '8020002000301',
        sku: 'DEN-JEA-BD-46',
        stock: 15,
        priceAdjustment: 0,
      },
      {
        id: 'var-2-4',
        size: '48',
        color: 'Blu Scuro',
        barcode: '8020002000401',
        sku: 'DEN-JEA-BD-48',
        stock: 10,
        priceAdjustment: 0,
      },
      {
        id: 'var-2-5',
        size: '42',
        color: 'Nero',
        barcode: '8020002000102',
        sku: 'DEN-JEA-N-42',
        stock: 6,
        priceAdjustment: 5.00,
      },
      {
        id: 'var-2-6',
        size: '44',
        color: 'Nero',
        barcode: '8020002000202',
        sku: 'DEN-JEA-N-44',
        stock: 10,
        priceAdjustment: 5.00,
      },
      {
        id: 'var-2-7',
        size: '46',
        color: 'Nero',
        barcode: '8020002000302',
        sku: 'DEN-JEA-N-46',
        stock: 12,
        priceAdjustment: 5.00,
      },
      {
        id: 'var-2-8',
        size: '48',
        color: 'Nero',
        barcode: '8020002000402',
        sku: 'DEN-JEA-N-48',
        stock: 8,
        priceAdjustment: 5.00,
      },
    ],
  },

  // Giacca Unisex
  {
    id: 'fashion-3',
    name: 'Giacca Bomber Unisex',
    description: 'Giacca bomber stile urban',
    price: 129.90,
    category: 'cat-2',
    barcode: '8020003000001',
    stock: 0,
    taxRate: 22,
    active: true,
    brand: 'UrbanStyle',
    season: 'AI',
    gender: 'unisex',
    composition: '100% Poliestere',
    variants: [
      {
        id: 'var-3-1',
        size: 'S',
        color: 'Nero',
        barcode: '8020003000101',
        sku: 'URB-BOM-N-S',
        stock: 5,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-2',
        size: 'M',
        color: 'Nero',
        barcode: '8020003000201',
        sku: 'URB-BOM-N-M',
        stock: 8,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-3',
        size: 'L',
        color: 'Nero',
        barcode: '8020003000301',
        sku: 'URB-BOM-N-L',
        stock: 6,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-4',
        size: 'XL',
        color: 'Nero',
        barcode: '8020003000401',
        sku: 'URB-BOM-N-XL',
        stock: 4,
        priceAdjustment: 10.00,
      },
      {
        id: 'var-3-5',
        size: 'S',
        color: 'Kaki',
        barcode: '8020003000102',
        sku: 'URB-BOM-K-S',
        stock: 4,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-6',
        size: 'M',
        color: 'Kaki',
        barcode: '8020003000202',
        sku: 'URB-BOM-K-M',
        stock: 7,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-7',
        size: 'L',
        color: 'Kaki',
        barcode: '8020003000302',
        sku: 'URB-BOM-K-L',
        stock: 5,
        priceAdjustment: 0,
      },
      {
        id: 'var-3-8',
        size: 'S',
        color: 'Bordeaux',
        barcode: '8020003000103',
        sku: 'URB-BOM-BO-S',
        stock: 3,
        priceAdjustment: 10.00,
      },
      {
        id: 'var-3-9',
        size: 'M',
        color: 'Bordeaux',
        barcode: '8020003000203',
        sku: 'URB-BOM-BO-M',
        stock: 6,
        priceAdjustment: 10.00,
      },
    ],
  },

  // Vestito Donna
  {
    id: 'fashion-4',
    name: 'Vestito Donna Elegante',
    description: 'Vestito midi elegante',
    price: 89.90,
    category: 'cat-2',
    barcode: '8020004000001',
    stock: 0,
    taxRate: 22,
    active: true,
    brand: 'EleganzaFit',
    season: 'PE',
    gender: 'donna',
    composition: '70% Viscosa, 30% Poliestere',
    variants: [
      {
        id: 'var-4-1',
        size: '38',
        color: 'Rosso',
        barcode: '8020004000101',
        sku: 'ELE-VES-R-38',
        stock: 4,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-2',
        size: '40',
        color: 'Rosso',
        barcode: '8020004000201',
        sku: 'ELE-VES-R-40',
        stock: 6,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-3',
        size: '42',
        color: 'Rosso',
        barcode: '8020004000301',
        sku: 'ELE-VES-R-42',
        stock: 5,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-4',
        size: '44',
        color: 'Rosso',
        barcode: '8020004000401',
        sku: 'ELE-VES-R-44',
        stock: 3,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-5',
        size: '38',
        color: 'Blu Elettrico',
        barcode: '8020004000102',
        sku: 'ELE-VES-BE-38',
        stock: 5,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-6',
        size: '40',
        color: 'Blu Elettrico',
        barcode: '8020004000202',
        sku: 'ELE-VES-BE-40',
        stock: 7,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-7',
        size: '42',
        color: 'Blu Elettrico',
        barcode: '8020004000302',
        sku: 'ELE-VES-BE-42',
        stock: 4,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-8',
        size: '40',
        color: 'Nero',
        barcode: '8020004000203',
        sku: 'ELE-VES-N-40',
        stock: 8,
        priceAdjustment: 0,
      },
      {
        id: 'var-4-9',
        size: '42',
        color: 'Nero',
        barcode: '8020004000303',
        sku: 'ELE-VES-N-42',
        stock: 6,
        priceAdjustment: 0,
      },
    ],
  },
];
