import type { Product, Category, Operator, Discount, LoyaltyCard } from '../types';

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Elettronica', icon: '📱', color: '#3b82f6' },
  { id: 'cat-2', name: 'Abbigliamento', icon: '👕', color: '#8b5cf6' },
  { id: 'cat-3', name: 'Alimentari', icon: '🍕', color: '#10b981' },
  { id: 'cat-4', name: 'Casa e Giardino', icon: '🏡', color: '#f59e0b' },
  { id: 'cat-5', name: 'Sport', icon: '⚽', color: '#ef4444' },
  { id: 'cat-6', name: 'Libri', icon: '📚', color: '#6366f1' },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Smartphone Galaxy X',
    description: 'Smartphone di ultima generazione con camera 48MP',
    price: 599.99,
    category: 'cat-1',
    barcode: '8012345678901',
    stock: 25,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-2',
    name: 'Cuffie Wireless Pro',
    description: 'Cuffie con cancellazione del rumore',
    price: 149.99,
    category: 'cat-1',
    barcode: '8012345678902',
    stock: 50,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-3',
    name: 'T-Shirt Basic',
    description: 'T-shirt in cotone 100%',
    price: 19.99,
    category: 'cat-2',
    barcode: '8012345678903',
    stock: 100,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-4',
    name: 'Jeans Slim Fit',
    description: 'Jeans elasticizzati comfort fit',
    price: 59.99,
    category: 'cat-2',
    barcode: '8012345678904',
    stock: 75,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-5',
    name: 'Pasta Italiana 500g',
    description: 'Pasta di semola di grano duro',
    price: 1.99,
    category: 'cat-3',
    barcode: '8012345678905',
    stock: 200,
    taxRate: 10,
    active: true,
  },
  {
    id: 'prod-6',
    name: 'Olio Extra Vergine 1L',
    description: 'Olio extravergine di oliva DOP',
    price: 12.99,
    category: 'cat-3',
    barcode: '8012345678906',
    stock: 80,
    taxRate: 10,
    active: true,
  },
  {
    id: 'prod-7',
    name: 'Set Pentole Inox',
    description: 'Set 5 pentole in acciaio inox',
    price: 89.99,
    category: 'cat-4',
    barcode: '8012345678907',
    stock: 30,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-8',
    name: 'Lampada LED',
    description: 'Lampada da tavolo a LED dimmerabile',
    price: 34.99,
    category: 'cat-4',
    barcode: '8012345678908',
    stock: 45,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-9',
    name: 'Pallone da Calcio',
    description: 'Pallone professionale taglia 5',
    price: 24.99,
    category: 'cat-5',
    barcode: '8012345678909',
    stock: 60,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-10',
    name: 'Tappetino Yoga',
    description: 'Tappetino antiscivolo 180x60cm',
    price: 29.99,
    category: 'cat-5',
    barcode: '8012345678910',
    stock: 40,
    taxRate: 22,
    active: true,
  },
  {
    id: 'prod-11',
    name: 'Il Signore degli Anelli',
    description: 'Edizione completa della trilogia',
    price: 39.99,
    category: 'cat-6',
    barcode: '8012345678911',
    stock: 20,
    taxRate: 4,
    active: true,
  },
  {
    id: 'prod-12',
    name: 'Guida Pratica Python',
    description: 'Manuale completo per programmatori',
    price: 44.99,
    category: 'cat-6',
    barcode: '8012345678912',
    stock: 35,
    taxRate: 4,
    active: true,
  },
];

export const mockOperators: Operator[] = [
  {
    id: 'op-1',
    name: 'Mario Rossi',
    email: 'mario.rossi@shop.it',
    role: 'admin',
    pin: '1234',
    active: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'op-2',
    name: 'Laura Bianchi',
    email: 'laura.bianchi@shop.it',
    role: 'cashier',
    pin: '5678',
    active: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'op-3',
    name: 'Giuseppe Verdi',
    email: 'giuseppe.verdi@shop.it',
    role: 'manager',
    pin: '9012',
    active: true,
    createdAt: new Date('2024-02-01'),
  },
];

export const mockDiscounts: Discount[] = [
  {
    id: 'disc-1',
    type: 'percentage',
    value: 10,
    description: 'Sconto 10%',
    active: true,
  },
  {
    id: 'disc-2',
    type: 'percentage',
    value: 20,
    description: 'Sconto 20%',
    active: true,
  },
  {
    id: 'disc-3',
    type: 'percentage',
    value: 50,
    description: 'Super Sconto 50%',
    active: true,
  },
  {
    id: 'disc-4',
    type: 'fixed',
    value: 5,
    description: 'Sconto €5',
    active: true,
  },
  {
    id: 'disc-5',
    type: 'fixed',
    value: 10,
    description: 'Sconto €10',
    active: true,
  },
  {
    id: 'disc-6',
    type: 'coupon',
    value: 15,
    code: 'WELCOME15',
    description: 'Coupon Benvenuto -15%',
    minAmount: 50,
    active: true,
  },
];

export const mockLoyaltyCards: LoyaltyCard[] = [
  {
    id: 'lc-1',
    cardNumber: 'LC001234',
    customerName: 'Anna Romano',
    customerEmail: 'anna.romano@email.it',
    customerPhone: '+39 320 1234567',
    points: 450,
    level: 'gold',
    discount: 10,
    createdAt: new Date('2024-01-10'),
    lastUsed: new Date('2024-11-10'),
  },
  {
    id: 'lc-2',
    cardNumber: 'LC001235',
    customerName: 'Marco Ferrari',
    customerEmail: 'marco.ferrari@email.it',
    customerPhone: '+39 320 7654321',
    points: 180,
    level: 'silver',
    discount: 5,
    createdAt: new Date('2024-03-15'),
    lastUsed: new Date('2024-11-12'),
  },
  {
    id: 'lc-3',
    cardNumber: 'LC001236',
    customerName: 'Giulia Costa',
    customerEmail: 'giulia.costa@email.it',
    customerPhone: '+39 320 9876543',
    points: 890,
    level: 'platinum',
    discount: 15,
    createdAt: new Date('2023-11-01'),
    lastUsed: new Date('2024-11-13'),
  },
];
