import type { Store } from '../types';

// Mock data - in produzione verrebbe da API
export const mockStores: Store[] = [
  // Fashion - Eleganza Fashion Group
  {
    id: 'store-1',
    businessId: 'bus-1',
    name: 'Eleganza Milano Montenapoleone',
    code: 'EFG-MI-001',
    address: 'Via Montenapoleone 8',
    city: 'Milano',
    province: 'MI',
    postalCode: '20121',
    phone: '+39 02 7601 3456',
    email: 'milano@eleganzafashion.it',
    sector: 'fashion',
    active: true,
    createdAt: new Date('2023-06-15'),
    openingHours: {
      monday: { open: '10:00', close: '19:30', closed: false },
      tuesday: { open: '10:00', close: '19:30', closed: false },
      wednesday: { open: '10:00', close: '19:30', closed: false },
      thursday: { open: '10:00', close: '19:30', closed: false },
      friday: { open: '10:00', close: '19:30', closed: false },
      saturday: { open: '10:00', close: '20:00', closed: false },
      sunday: { open: '11:00', close: '19:00', closed: false },
    },
    cashRegisterCode: 'EFG-CR-001',
    fiscalPrinterSerial: 'RT-EFG-001-2023',
  },

  {
    id: 'store-2',
    businessId: 'bus-1',
    name: 'Eleganza Roma Via Condotti',
    code: 'EFG-RM-002',
    address: 'Via Condotti 67',
    city: 'Roma',
    province: 'RM',
    postalCode: '00187',
    phone: '+39 06 6992 1845',
    email: 'roma@eleganzafashion.it',
    sector: 'fashion',
    active: true,
    createdAt: new Date('2023-09-01'),
    openingHours: {
      monday: { open: '10:00', close: '19:30', closed: false },
      tuesday: { open: '10:00', close: '19:30', closed: false },
      wednesday: { open: '10:00', close: '19:30', closed: false },
      thursday: { open: '10:00', close: '19:30', closed: false },
      friday: { open: '10:00', close: '19:30', closed: false },
      saturday: { open: '10:00', close: '20:00', closed: false },
      sunday: { open: '', close: '', closed: true },
    },
    cashRegisterCode: 'EFG-CR-002',
    fiscalPrinterSerial: 'RT-EFG-002-2023',
  },

  // Bar - Caffè Da Vinci
  {
    id: 'store-3',
    businessId: 'bus-2',
    name: 'Caffè Da Vinci Navona',
    code: 'CDV-RM-001',
    address: 'Piazza Navona 47',
    city: 'Roma',
    province: 'RM',
    postalCode: '00186',
    phone: '+39 06 6854 2190',
    email: 'navona@caffedavinci.com',
    sector: 'bar',
    active: true,
    createdAt: new Date('2024-01-10'),
    openingHours: {
      monday: { open: '06:30', close: '22:00', closed: false },
      tuesday: { open: '06:30', close: '22:00', closed: false },
      wednesday: { open: '06:30', close: '22:00', closed: false },
      thursday: { open: '06:30', close: '22:00', closed: false },
      friday: { open: '06:30', close: '23:00', closed: false },
      saturday: { open: '07:00', close: '23:00', closed: false },
      sunday: { open: '07:30', close: '21:00', closed: false },
    },
    cashRegisterCode: 'CDV-CR-001',
    fiscalPrinterSerial: 'RT-CDV-001-2024',
  },

  {
    id: 'store-4',
    businessId: 'bus-2',
    name: 'Caffè Da Vinci Trastevere',
    code: 'CDV-RM-002',
    address: 'Via della Lungaretta 86',
    city: 'Roma',
    province: 'RM',
    postalCode: '00153',
    phone: '+39 06 5833 7421',
    email: 'trastevere@caffedavinci.com',
    sector: 'bar',
    active: true,
    createdAt: new Date('2024-02-15'),
    openingHours: {
      monday: { open: '07:00', close: '21:00', closed: false },
      tuesday: { open: '07:00', close: '21:00', closed: false },
      wednesday: { open: '07:00', close: '21:00', closed: false },
      thursday: { open: '07:00', close: '21:00', closed: false },
      friday: { open: '07:00', close: '22:00', closed: false },
      saturday: { open: '07:00', close: '22:00', closed: false },
      sunday: { open: '08:00', close: '20:00', closed: false },
    },
    cashRegisterCode: 'CDV-CR-002',
    fiscalPrinterSerial: 'RT-CDV-002-2024',
  },

  // Restaurant - Trattoria Toscana
  {
    id: 'store-5',
    businessId: 'bus-3',
    name: 'Trattoria Toscana Firenze Centro',
    code: 'TT-FI-001',
    address: 'Via dei Calzaiuoli 32',
    city: 'Firenze',
    province: 'FI',
    postalCode: '50122',
    phone: '+39 055 284 735',
    email: 'centro@trattoriatoscana.it',
    sector: 'restaurant',
    active: true,
    createdAt: new Date('2023-03-20'),
    openingHours: {
      monday: { open: '12:00', close: '15:00', closed: false }, // Pranzo e cena
      tuesday: { open: '12:00', close: '15:00', closed: false },
      wednesday: { open: '12:00', close: '23:00', closed: false },
      thursday: { open: '12:00', close: '23:00', closed: false },
      friday: { open: '12:00', close: '23:30', closed: false },
      saturday: { open: '12:00', close: '23:30', closed: false },
      sunday: { open: '12:00', close: '22:00', closed: false },
    },
    cashRegisterCode: 'TT-CR-001',
    fiscalPrinterSerial: 'RT-TT-001-2023',
  },

  // Fashion - SportWear Italia
  {
    id: 'store-6',
    businessId: 'bus-4',
    name: 'SportWear Torino Centro',
    code: 'SWI-TO-001',
    address: 'Corso Vittorio Emanuele II 76',
    city: 'Torino',
    province: 'TO',
    postalCode: '10121',
    phone: '+39 011 543 8921',
    email: 'torino@sportwearitalia.it',
    sector: 'fashion',
    active: true,
    createdAt: new Date('2024-02-01'),
    openingHours: {
      monday: { open: '09:00', close: '19:30', closed: false },
      tuesday: { open: '09:00', close: '19:30', closed: false },
      wednesday: { open: '09:00', close: '19:30', closed: false },
      thursday: { open: '09:00', close: '19:30', closed: false },
      friday: { open: '09:00', close: '19:30', closed: false },
      saturday: { open: '09:00', close: '20:00', closed: false },
      sunday: { open: '10:00', close: '13:00', closed: false }, // Domenica solo mattina
    },
    cashRegisterCode: 'SWI-CR-001',
    fiscalPrinterSerial: 'RT-SWI-001-2024',
  },

  // Bar - Dolce Vita Pasticceria
  {
    id: 'store-7',
    businessId: 'bus-5',
    name: 'Dolce Vita Toledo',
    code: 'DVP-NA-001',
    address: 'Via Toledo 156',
    city: 'Napoli',
    province: 'NA',
    postalCode: '80134',
    phone: '+39 081 764 5321',
    email: 'toledo@dolcevitapasticceria.it',
    sector: 'bar',
    active: true,
    createdAt: new Date('2024-03-15'),
    openingHours: {
      monday: { open: '06:00', close: '20:00', closed: false },
      tuesday: { open: '06:00', close: '20:00', closed: false },
      wednesday: { open: '06:00', close: '20:00', closed: false },
      thursday: { open: '06:00', close: '20:00', closed: false },
      friday: { open: '06:00', close: '20:30', closed: false },
      saturday: { open: '06:00', close: '20:30', closed: false },
      sunday: { open: '07:00', close: '14:00', closed: false }, // Domenica solo mattina
    },
    cashRegisterCode: 'DVP-CR-001',
    fiscalPrinterSerial: 'RT-DVP-001-2024',
  },

  // Restaurant - Pizzeria Napoletana
  {
    id: 'store-8',
    businessId: 'bus-6',
    name: 'Pizzeria Tradizione Venezia',
    code: 'PNT-VE-001',
    address: 'Campo Santa Maria Formosa 5252',
    city: 'Venezia',
    province: 'VE',
    postalCode: '30122',
    phone: '+39 041 528 6743',
    email: 'venezia@tradizionenapoli.com',
    sector: 'restaurant',
    active: true,
    createdAt: new Date('2023-09-01'),
    openingHours: {
      monday: { open: '18:30', close: '23:00', closed: false }, // Solo cena
      tuesday: { open: '18:30', close: '23:00', closed: false },
      wednesday: { open: '', close: '', closed: true }, // Chiuso
      thursday: { open: '18:30', close: '23:00', closed: false },
      friday: { open: '18:30', close: '23:30', closed: false },
      saturday: { open: '12:00', close: '23:30', closed: false }, // Pranzo e cena weekend
      sunday: { open: '12:00', close: '22:30', closed: false },
    },
    cashRegisterCode: 'PNT-CR-001',
    fiscalPrinterSerial: 'RT-PNT-001-2023',
  },

  // Generic - La Matita Magica
  {
    id: 'store-9',
    businessId: 'bus-7',
    name: 'La Matita Magica Bologna',
    code: 'LMM-BO-001',
    address: 'Via Rizzoli 18',
    city: 'Bologna',
    province: 'BO',
    postalCode: '40125',
    phone: '+39 051 234 8765',
    email: 'bologna@lamatitamagica.it',
    sector: 'generic',
    active: true,
    createdAt: new Date('2024-04-01'),
    openingHours: {
      monday: { open: '09:00', close: '13:00', closed: false }, // Orario continuato + pausa pranzo
      tuesday: { open: '09:00', close: '19:00', closed: false },
      wednesday: { open: '09:00', close: '19:00', closed: false },
      thursday: { open: '09:00', close: '13:00', closed: false },
      friday: { open: '09:00', close: '19:00', closed: false },
      saturday: { open: '09:00', close: '19:00', closed: false },
      sunday: { open: '', close: '', closed: true },
    },
    cashRegisterCode: 'LMM-CR-001',
    fiscalPrinterSerial: 'RT-LMM-001-2024',
  },
];

// Funzione helper per trovare uno store per ID
export const getStoreById = (id: string): Store | undefined => {
  return mockStores.find((s) => s.id === id);
};
